<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}
/* MODIFIACTION theme-style.cc & style.css */
.create_album_images .upload-product-image:hover .upload-image-content {background-color: #ffbcac;}
.create_album_images .upload-product-image .upload-image-content {color: #ef2362;border: 2px dashed #ed186f;background-color: #ffe6de;}
.sun_head_onboard.album {background-color: #f95329;}
.member_list,.adv-mbr-search,.g_search, .bg-main, .blocksubhead {background-color: #f23053 !important;}
.sun_head_onboard {background-color: #f35d4d;}
.my_pages_header ul li.active a {background: #f12c57;}
.my_pages_header .btn.create_album_btn {background: #fc6019;}
.sun_head_onboard.group {background-color: #f95329;}
.sun_blog_head {background: linear-gradient(135deg, #ed186f 0%,#fc6019 100%);}
input.cusrange[type=range]::-moz-range-thumb {background-color: #fa5428;}
.sun_find_frns_hdr .btn {background: linear-gradient(135deg, #ed186f 0%,#fc6019 100%);}
.sun_find_frns_hdr .btn:hover {background: linear-gradient(135deg, #993d63 0%,#f37439 100%);}
.wo-create-forms .wo_create_form_cover:before {background-image: linear-gradient(135deg, #ed186f 0%,#fc6019 100%);}
.wo-create-forms .wo_create_form_cover.blog:before {background-image: linear-gradient(135deg, #ed186f 0%,#fc6019 100%)}



/* SEARCHBAR STYLE */
.search-dropdown-container {
	width: 300px;
}
.search-container .search-input {
	transition: all .3s;
	border-radius: 3px;
	border-color: transparent;
	width: 300px;
	height: 30px;
	color: #777;
	box-shadow: none;
	padding-left: 25px;
	background: 0 0
    
}

.search-container .search-input:focus {
	background: #fff;
	color: #333
}

.search-container .inner-addon .glyphicon {
	padding: 0!important;
	color: #898d94 !important;
	margin: 5px 0 5px 5px;
	width: 16px;
	height: 16px
    
}

.search-container .search-input::placeholder {
	color: #898d94 !important;
}

.navbar-nav.left_part_header .search-container .head_clos_srch {
	position: absolute;
	top: 9.5px;
	right: 8px;
	color: white;
	height: 24px;
	width: 24px;
	cursor: pointer;
	z-index: 9;
}

body.search_open .navbar-nav.left_part_header .search-container {
	top: 0;
}

.navbar-nav.left_part_header .search-container {
	float: none;
	position: absolute;
	transition: all 0.2s;
	z-index: 999;
	height: 45px;
    top: auto;
    margin-left: 170px;
    width: 315px;
}
/* SEARCHBAR STYLE END */

.navbar-default {
    /*background: #f32655; border: none;*/
    /*background: #f32655; border: none;*/
    background:linear-gradient(120deg, rgba(236,17,106,0.9700922605370274) 20%, rgba(252,91,18,0.9700922605370274) 60%) !important;
    height:45px;box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2);
}
.navbar-nav.left_part_header .search-container {
	/*background: #f32655;*/
	background: none !important;
}
.round-check input[type="checkbox"]:checked + label:before {
    background: #f32655 !important;
}
.group-messages-wrapper a{
    color: #f32655 !important;
}
ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: #f32655 !important;
}
.featured-users{
    background: #fff !important;
}
.result-bar {
    background: #f32655 !important;
}
.avtive {
    border-color: #f32655 !important;
}
.left-sidebar ul li a i {
    color: #f32655 !important;
}
.cs-loader-inner, .main  {
    color: #f32655;
}
.login input:focus, ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper {
    border-color: #f32655 !important;
}
.login:not(.loading) button:hover {
    background: #2e7be5 !important;
    color: #ffffff;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle{
    border-color: #f32655;
}
#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after{
    background: #f32655;
}
.login button, .wo_search_page .nav-tabs li.active a {
    background: #f32655 !important;
    color: #ffffff !important;
}

.mejs-controls .mejs-time-rail .mejs-time-current, .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current, .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: #f32655 !important;
    background: #f32655 !important;
    background-image: #f32655 !important;
}
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    /*background-color: #2e7be5 !important;*/
    background-color: #e91e63 !important;
}
.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .nav-names li:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
body {
    background-color: <?php echo $wo['config']['body_background'];?>;
}
.navbar-default .navbar-nav>li>a {
    color: <?php echo $wo['config']['header_color'];?>;
    font-size: 13px;
}
a.unread-update, .head_clos_srch {
    color: #898d94 !important;  /*<?php echo $wo['config']['header_color'];?>*/
}
.btn-main {
    color: #ffffff;
    background-color: #f32655;
    border-color: #f32655;
}
.btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: #2e7be5;
    border-color: #2e7be5;
}
.active-wonder {
    color: #f32655;
}
.admin-panel .col-md-9 .list-group-item:first-child, .setting-panel .col-md-8 .list-group-item:first-child, .profile-lists .list-group-item:first-child, .col-md-8 .list-group-item:first-child, .col-md-3.custom .list-group-item:first-child, .col-sm-4 .list-group-item:first-child, .col-md-7 .list-group-item:first-child, .col-md-9 .list-group-item:first-child, .red-list .list-group-item:first-child, .active.list-group-item:first-child {
     color: #444;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
}
.admin-panel .col-md-9 .list-group-item:first-child a, .setting-panel .col-md-8 .list-group-item:first-child a, .profile-lists .list-group-item:first-child a, .col-md-8 .list-group-item:first-child a, .col-md-7 .list-group-item:first-child a, .active.list-group-item:first-child a {
    color: #444 !important;
}
.list-group-item.black-list.active-list, .red-list.active-list {
    color: #ffffff;
    background-color: #f32655;
}
.list-group-item.black-list {
    background: #f32655;
}
.profile-top-line {
    background-color: #f32655;
}
#bar {
    background-color: #f32655;
}
.list-group-item.black-list a{
    color: #ffffff;
}
.list-group-item.black-list.active-list a{
    color: #f32655;
}
.main-color, .small-text a {
    color: #f32655 !important;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: #ffffff;
    cursor: default;
    color: #f32655;
    border-bottom: 1px solid #f32655;
    background-color: transparent
}
.btn-active {
    color: #ffffff;
    background: #f32655;
    outline: none;
    border: 1px solid #f32655
}
.btn-active:hover, .btn-active:focus {
    border: 1px solid #2e7be5;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: #2e7be5;
}
.btn-active-color:hover {
    background: #2e7be5;
}
.chat-tab .online-toggle {
    background: #f32655;
}
.profile-style .user-follow-button button.btn-active, .btn-login, .btn-register {
    background: #f32655;
    color: #ffffff;
}
.profile-style .user-follow-button button.btn-active:hover, .btn-login:hover, .btn-login:focus, .btn-register:hover, .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: #2e7be5;
}
.panel-login>.panel-heading a.active {
    color: #f32655;
    font-size: 18px;
}
.hash {
    color: #f32655;
}
.message-text .hash {
    color: #fff !important;
}
.search-container .search-input{
    color: #898d94!important;
    background: #fff !important;
}
.chat-messages-wrapper .outgoing {
    background: #f32655;
}
.message p {
    color: #fff;
}
.text-sender-container .outgoing .message-model .message {
    background: #f32655;
}
 
.incoming .message. p {
    color: #555;
}
.incoming.message p {
    color: #555;
}
.incoming .message p {
    color: #555;
}
.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.active.fa-thumbs-up {
    color: #f32655;
}
.api-ex-urls {
    background-color: #f32655; color: #ffffff;
}
.user-username {
    color: #f32655;
}
.upload-image {
    border: 3px dashed #f32655;
}

/* COLORS */
.sun_comm_addmore > .dropdown-toggle {color: #fc6019 !important;}
.btn-add-comm-postt {
	color: #f3374a !important;
}
.search-container .inner-addon .glyphicon {
	color: #898d94 !important;
}
.search-container .search-input::placeholder {
	color: #898d94 !important;
}
/* END OF COLORS */

.events-tab-list li { background-color: #f32655; }
.events-tab-list li:hover { background-color: #f32655; }
.active-e-tab { background-color: #f32655 !important; }
.main { color: #f32655 !important; }
.events-list-dropup-menu ul li a:hover { background: #f32655; }
.usr-offline { color: #f32655; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: #f32655 !important; }
.blog_publ {background: #f32655 ; border: 1px solid #f32655 ; }

.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
    color: #f32655 !important;
}
.movies h3.latest-movies, h3.recommended-movies {
    border-left: 3px solid  #f32655;
}

.wo_user_profile .user-bottom-nav li .menuactive {
    border-bottom: 2px solid #f32655;
    color:#f32655;
}


<?php 
if ($wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != '404' && $wo['page'] != 'movies' && $wo['loggedin'] == true && $wo['page'] != 'messages' && $wo['page'] != 'start_up') { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-right: 205px;}
@media (min-width: 1420px) {
body, .navbar-default, .wo_about_wrapper_parent{padding-right: 240px;}.sun_blog_head {right: 240px;}
}
@media (max-width:1140px){.wo_about_wrapper_parent{padding-right: 0px;}}
.sun_blog_head {right: 205px;}
<?php } ?>

<?php if($wo['language_type'] == 'rtl' && $wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != '404' && $wo['page'] != 'movies' && $wo['page'] != 'messages' && $wo['page'] != 'start_up' && $wo['loggedin'] == true) { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-left: 205px;padding-right: 0px;}
@media (max-width:1140px){.wo_about_wrapper_parent{padding-left: 0px;}}
<?php } ?>

.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px #f32655 !important;
}

.ui-widget-header .ui-state-default {
    background-color: #f32655;
}

<?php
if (!empty($wo['reactions_types'])) {
    foreach ($wo['reactions_types'] as $key => $value) {
?>
.reaction-<?php echo $value['id'];?>::before {
    content: "<?php echo $value['name'];?>";
}
<?php } } ?>
/*.reaction-like::before {
    content: "<?php echo $wo['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $wo['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $wo['lang']['haha'];?>";
}
.reaction-wow::before {
    content: "<?php echo $wo['lang']['wow'];?>";
}
.reaction-sad::before {
    content: "<?php echo $wo['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $wo['lang']['angry'];?>";
}*/

.navbar-default .dropdown-menu.ani-acc-menu >li>a:hover {
    color: #ffffff;background-color: #f32655;
}

@media (min-width: 992px){
#wo_msg_right_prt .text-sender-container .outgoing .message-model .message p {
    color: #ffffff;background-color: #f32655;
}

#wo_nw_msg_page .messages-recipients-list .msg_ava_name {
    color: <?php echo $wo['config']['header_color'];?> !important;
}
#wo_nw_msg_page .messages-recipients-list.active .msg_ava_name {
    color: #333 !important;
}
}
<?php if ($wo['config']['google_map'] == 0) { ?>
#filterby-post li {
    width: 16.5%;
}
<?php }?>


.sun_input input:focus, .sun_input textarea:focus, .sun_input select:focus{border-color:#f32655}
.loading::before {background-color: #f32655;}

<?php if($wo['page'] == 'home') { ?>
#wo_post_stat_button > .stat-item:nth-child(2) svg {
	margin-right: 3px;
}
<?php } ?>

<?php if($wo['language'] == 'russian') { ?>
.wo_market .market_bottom .product .product-links .info-middle .more-info {
    padding: 0px 15px;
    margin: 0px 3px;
}
<?php } ?>

<?php if($wo['language'] == 'spanish') { ?>
@media (min-width: 600px) {
.sun_pub_mid_foot .poster-left-buttons:last-child {
    max-width: 100px;
}
.sun_pub_mid_foot .poster-left-buttons:last-child .btn {
    max-width: 100px;
}
.sun_pub_mid_foot .poster-left-buttons:last-child .btn span {
    max-width: calc(100% - 22px);
    display: inline-block;
    overflow: hidden;
    text-overflow: ellipsis;
    vertical-align: bottom;
}
}
<?php } ?>
</style>